# Autor: Carlos Lopez
# Date: 16/03/2025

OrdererOrgs:
    - Name: GobiernoDelEcuador
      Domain: gob.ec
      EnableNodeOUs: true
      Specs:
        - Hostname: orderer
          SANS:
            - localhost
PeerOrgs:
    - Name: RegistroCivil
      Domain: registrocivil.gob.ec
      EnableNodeOUs: true
      Template:
        Count: 1
        SANS:
          - localhost
      Users:
        Count: 1
    - Name: Cne
      Domain: cne.gob.ec
      EnableNodeOUs: true
      Template:
        Count: 1
        SANS:
          - localhost
      Users:
        Count: 1
    - Name: Ant
      Domain: ant.gob.ec
      EnableNodeOUs: true    
      Template:
        Count: 1
        SANS:
          - localhost
      Users:
        Count: 1
    - Name: Dirección Nacional de Registros Públicos
      Domain: dinardarp.gob.ec
      EnableNodeOUs: true    
      Template:
        Count: 1
        SANS:
          - localhost
      Users:
        Count: 1
  